import LocationSection from "../sections/LocationSection/LocationSection";
import MainSection from "../sections/MainSection/MainSection";
import MenuSection from "../sections/MenuSection/MenuSection";
import {MenuItem} from "../types/types";

export const SECTIONS = [
  {id: 0, component: MainSection},
  {id: 1, component: MenuSection},
  {id: 2, component: LocationSection},
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    name: {kor: "바닐라빈라떼", eng: "Vanilla Bean Latte"},
    category: "Coffee",
    price: 5000,
    isNew: false,
    isRecommended: false,
    description: {
      kor: "바닐라빈이 콕콕 박혀있어 바닐라의 풍미가 살아있는 달달한 라떼",
      eng: "A sweet latte with the flavor of vanilla, studded with vanilla beans.",
    },
  },
  {
    id: 2,
    name: {kor: "아포가또", eng: "Affogato"},
    category: "Coffee",
    price: 5500,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 3,
    name: {kor: "아메리카노", eng: "Americano"},
    category: "Coffee",
    price: 4000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 4,
    name: {kor: "헤이즐넛크림커피", eng: "Hazelnut Cream Coffee"},
    category: "Coffee",
    price: 5800,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 5,
    name: {kor: "아메리카노오렌지", eng: "Americano Orange"},
    category: "Coffee",
    price: 4800,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 6,
    name: {kor: "카푸치노", eng: "Cappuccino"},
    category: "Coffee",
    price: 4600,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 7,
    name: {kor: "카페라떼", eng: "Caffe Latte"},
    category: "Coffee",
    price: 4600,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 8,
    name: {kor: "오렌지비앙코", eng: "Orange Bianco"},
    category: "Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 9,
    name: {kor: "블루베리라떼 위드샷", eng: "Blueberry Latte with Shot"},
    category: "Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 10,
    name: {kor: "바나나라떼 위드샷", eng: "Banana Latte with Shot"},
    category: "Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 11,
    name: {kor: "카페모카", eng: "Caffe Mocha"},
    category: "Coffee",
    price: 5000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 12,
    name: {kor: "스파클링 아메리카노", eng: "Sparkling Americano"},
    category: "Coffee",
    price: 5000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 13,
    name: {kor: "버터커피", eng: "Butter Coffee"},
    category: "Coffee",
    price: 5000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 14,
    name: {kor: "바나나오트밀쉐이크", eng: "Banana Oatmeal Shake"},
    category: "Non-Coffee",
    price: 6500,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 15,
    name: {kor: "제주말차라떼", eng: "Jeju Matcha Latte"},
    category: "Non-Coffee",
    price: 5500,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 16,
    name: {kor: "더블초코라떼", eng: "Double Choco Latte"},
    category: "Non-Coffee",
    price: 5500,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 17,
    name: {kor: "[수제청] 청귤라임에이드", eng: "[Homemade] Cheonggyul Lime Ade"},
    category: "Non-Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 18,
    name: {kor: "[수제청] 유자자몽에이드", eng: "[Homemade] Yuzu Grapefruit Ade"},
    category: "Non-Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 19,
    name: {kor: "[수제청] 오레몬에이드", eng: "[Homemade] Orange Lemon Ade"},
    category: "Non-Coffee",
    price: 6300,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 20,
    name: {kor: "복숭아 아이스티", eng: "Peach Iced Tea"},
    category: "Non-Coffee",
    price: 4000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 21,
    name: {kor: "스파클링 말차", eng: "Sparkling Matcha"},
    category: "Non-Coffee",
    price: 6000,
    isNew: false,
    isRecommended: false,
  },
  {
    id: 22,
    name: {kor: "얼그레이 리저브", eng: "Earl Grey Reserve"},
    category: "Tea",
    price: 5500,
    isNew: false,
    isRecommended: false,
  },
];
